# Generated by Django 2.0.3 on 2018-05-25 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmenu',
            name='parentItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.itemMenu'),
        ),
    ]
